[PlayerBaseConfig]

AIControl=false ;AI控制
SuperweaponNoWait=false  ;超武无等待
InstantConstruction=false  ;瞬间建造
AIDifficulty=0 ;AI难度
StartDanmu=false ;弹幕互动总开关
InitialMoney=0 ;开局给钱
IQLevel=5 ;AI控制时IQ
IQLevel2=5 ;AI控制时IQ2
IsOnlineBattleDangerFunctionEnable=true  ;开启后数据不同步奔溃 仅调试用
ShowUnitName=true  ;默认是否显示单位信息

MOEMOE=MOEMOE ;MOEMOE
RandomInfantryUnitID=V3,ZEP,DRON,HTK,TNKD,TTNK,HIND,LTNK,SREF,MGTK,FV,YTNK,BFRT,TELE,CAOS,SCHP,MIND,DISK,SCHD
RandomInfantryUnitID2=SHK,ENGINEER,JUMPJET,GHOST,YURI,IVAN,DESO,DOG,CLEG,WEEDGUY,SPY,CCOMAND,PTROOP,CIVAN,YURIPR,SNIPE,TANY,FLAKT,GGI,INIT,BRUTE,STLN,ARND,LUNR
GenCount=5 ;生成数量
[GiftFxConfig]
小花花=Extension.CoraExtension.MainTools.GiveRandomAIMoney(1000)


[HotkeyConfig]
; 格式KEY(控制按键,按键)=完整名字空间加类.方法(参数)
KEY(MOD_CONTROL,VK_SPACE)=Extension.CoraExtension.MainTools.SwitchAIControl() ;AI/Player  Control切换

KEY(MOD_CONTROL,VK_Q)=Extension.CoraExtension.MainTools.SendCoraSpecialPlaceEvent("NukeSpecial") ;发送放置战术核弹事件
KEY(MOD_CONTROL,VK_W)=Extension.CoraExtension.MainTools.SendCoraSpecialPlaceEvent("LightningStormSpecial") ;发送放置闪电风暴事件
KEY(MOD_CONTROL,VK_E)=Extension.CoraExtension.MainTools.SendCoraSpecialPlaceEvent("PsychicDominatorSpecial") ;发送放置心灵支配事件
KEY(MOD_CONTROL,VK_R)=Extension.CoraExtension.MainTools.SendCoraSpecialPlaceEvent("IronCurtainSpecial") 


KEY(MOD_CONTROL,VK_A)=Extension.CoraExtension.MainTools.SendCoraSpecialPlaceEvent("MCVParadropSpecial") 
KEY(MOD_CONTROL,VK_S)=Extension.CoraExtension.MainTools.SendCoraSpecialPlaceEvent("TankParadropSpecial") 
KEY(MOD_CONTROL,VK_D)=Extension.CoraExtension.MainTools.SendCoraSpecialPlaceEvent("FightersParadropSpecial") 



KEY(MOD_CONTROL,VK_C)=Extension.CoraExtension.MainTools.GivePlayerMoney(10000) ;给自己钱

; KEY(MOD_CONTROL,VK_V)=Extension.CoraExtension.MainTools.SendProduceEvent("MGTK") ;发送生产事件

KEY(MOD_CONTROL,VK_B)=Extension.CoraExtension.MainTools.SendCoraPlaceEventEx("DISK") ;发送自定义放置事件
KEY(MOD_CONTROL,VK_N)=Extension.CoraExtension.MainTools.GenUnitRandom(false) ;生成随机单位
; KEY(MOD_CONTROL,VK_D)=Extension.CoraExtension.MainTools.SwitchDisplayUnitNames()
; KEY(MOD_CONTROL,VK_S)=Extension.CoraExtension.CoraUtils.ExportAllUnitUiNameAndID()


; KEY(MOD_CONTROL,VK_B)=Extension.CoraExtension.MainTools.PlayVox() 



;最后必须换行否则最后一条配置读不出G